# Generated by Django 6.0.5 on 2026-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
