# Generated by Django 6.0.5 on 2026-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0004_alter_aetherixprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
