# Generated by Django 6.0.5 on 2026-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0005_alter_aetherixprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixusers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
