# Generated by Django 6.0.5 on 2026-06-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0006_alter_aetherixusers_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetherixprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending'),
        ),
    ]
