# Generated by Django 6.0.5 on 2026-07-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0007_aetherixprofile_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENFDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENFDING'),
        ),
    ]
