# Generated by Django 6.0.5 on 2026-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0008_alter_aetherixprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetherixprofile',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
