# Generated by Django 6.0.5 on 2026-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0009_aetherixprofile_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING'),
        ),
    ]
