# Generated by Django 6.0.5 on 2026-07-31 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0010_alter_aetherixprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetherixusers',
            name='roles',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'admin')], default='User'),
        ),
        migrations.AlterField(
            model_name='aetherixusers',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aetherixusers',
            name='updated_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
