# Generated by Django 6.0.5 on 2026-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0011_aetherixusers_roles_alter_aetherixusers_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixusers',
            name='roles',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='User', max_length=10),
        ),
    ]
