# Generated by Django 6.0.5 on 2026-08-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0013_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
