# Generated by Django 6.0.5 on 2026-09-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0014_usersession_ip_address_usersession_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
