# Generated by Django 6.0.5 on 2026-05-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_aetherixcomplaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aetherixcomplaints',
            old_name='municipalilty',
            new_name='municipality',
        ),
        migrations.RemoveField(
            model_name='aetherixcomplaints',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='aetherixcomplaints',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
