# Generated by Django 6.0.5 on 2026-05-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_rename_municipalilty_aetherixcomplaints_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixcomplaints',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
