# Generated by Django 6.0.5 on 2026-06-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_aetherixcomplaints_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixcomplaints',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
