# Generated by Django 6.0.5 on 2026-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_alter_aetherixcomplaints_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetherixcomplaints',
            name='rejection_reason',
            field=models.TextField(default='no rejection'),
        ),
    ]
