# Generated by Django 6.0.5 on 2026-07-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_aetherixcomplaints_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aetherixcomplaints',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='aetherixcomplaints',
            name='status',
        ),
    ]
