# Generated by Django 6.0.5 on 2026-07-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_aetherixcomplaints_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetherixcomplaints',
            name='upvotes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
