# Generated by Django 6.0.5 on 2026-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_complaintupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetherixcomplaints',
            name='priority_score',
            field=models.FloatField(default=0.0, help_text='Calculated priority score based on severity, upvotes and days pending'),
        ),
    ]
