# Generated by Django 6.0.5 on 2026-08-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcategory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='complaint.department'),
        ),
    ]
