# Generated by Django 6.0.5 on 2026-08-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_complaintcategory_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='display_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
