# Generated by Django 6.0.5 on 2026-08-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0014_department_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
