# Generated by Django 6.0.5 on 2026-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0015_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetherixcomplaints',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aetherixcomplaints',
            name='forwarded_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aetherixcomplaints',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
