# Generated by Django 6.0.5 on 2026-09-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0016_aetherixcomplaints_forwarded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetherixcomplaints',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='aetherixcomplaints',
            name='priority_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Calculated priority score based on severity, upvotes and days pending'),
        ),
        migrations.AlterField(
            model_name='aetherixcomplaints',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('INPROGRESS', 'Inprogress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
